create sequence quote_categories_id_seq;

alter sequence quote_categories_id_seq owner to postgres;

grant select, update, usage on sequence quote_categories_id_seq to anon;

grant select, update, usage on sequence quote_categories_id_seq to authenticated;

grant select, update, usage on sequence quote_categories_id_seq to service_role;

create sequence quote_people_id_seq;

alter sequence quote_people_id_seq owner to postgres;

grant select, update, usage on sequence quote_people_id_seq to anon;

grant select, update, usage on sequence quote_people_id_seq to authenticated;

grant select, update, usage on sequence quote_people_id_seq to service_role;

create table api_keys
(
    id  bigint generated by default as identity
        primary key,
    key uuid default gen_random_uuid() not null
);

alter table api_keys
    owner to postgres;

grant select, update, usage on sequence api_keys_id_seq to anon;

grant select, update, usage on sequence api_keys_id_seq to authenticated;

grant select, update, usage on sequence api_keys_id_seq to service_role;

grant delete, insert, references, select, trigger, truncate, update on api_keys to anon;

grant delete, insert, references, select, trigger, truncate, update on api_keys to authenticated;

grant delete, insert, references, select, trigger, truncate, update on api_keys to service_role;

create table games
(
    id            bigint generated by default as identity
        primary key,
    name          varchar not null,
    current_round smallint
);

alter table games
    owner to postgres;

grant select, update, usage on sequence games_id_seq to anon;

grant select, update, usage on sequence games_id_seq to authenticated;

grant select, update, usage on sequence games_id_seq to service_role;

create table categories
(
    id      bigint generated by default as identity
        primary key,
    name    varchar,
    game_id bigint not null
        references games
            on update cascade on delete cascade
);

alter table categories
    owner to postgres;

grant select, update, usage on sequence categories_id_seq to anon;

grant select, update, usage on sequence categories_id_seq to authenticated;

grant select, update, usage on sequence categories_id_seq to service_role;

grant delete, insert, references, select, trigger, truncate, update on categories to anon;

grant delete, insert, references, select, trigger, truncate, update on categories to authenticated;

grant delete, insert, references, select, trigger, truncate, update on categories to service_role;

grant delete, insert, references, select, trigger, truncate, update on games to anon;

grant delete, insert, references, select, trigger, truncate, update on games to authenticated;

grant delete, insert, references, select, trigger, truncate, update on games to service_role;

create table people
(
    id      bigint generated by default as identity
        primary key,
    name    varchar not null,
    game_id bigint  not null
        references games
            on update cascade on delete cascade
);

alter table people
    owner to postgres;

grant select, update, usage on sequence people_id_seq to anon;

grant select, update, usage on sequence people_id_seq to authenticated;

grant select, update, usage on sequence people_id_seq to service_role;

grant delete, insert, references, select, trigger, truncate, update on people to anon;

grant delete, insert, references, select, trigger, truncate, update on people to authenticated;

grant delete, insert, references, select, trigger, truncate, update on people to service_role;

create table quotes
(
    id         bigint generated by default as identity
        primary key,
    content    varchar,
    full_quote varchar,
    round      smallint default '1'::smallint not null,
    game_id    bigint                         not null
        references games
            on update cascade on delete cascade
);

alter table quotes
    owner to postgres;

grant select, update, usage on sequence quotes_id_seq to anon;

grant select, update, usage on sequence quotes_id_seq to authenticated;

grant select, update, usage on sequence quotes_id_seq to service_role;

create table quote_categories
(
    quote_id    bigint not null
        references quotes
            on update cascade on delete cascade,
    category_id bigint not null
        references categories
            on update cascade on delete cascade,
    constraint quote_categories_pk
        primary key (category_id, quote_id)
);

alter table quote_categories
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on quote_categories to anon;

grant delete, insert, references, select, trigger, truncate, update on quote_categories to authenticated;

grant delete, insert, references, select, trigger, truncate, update on quote_categories to service_role;

create table quote_people
(
    quote_id  bigint not null
        references quotes
            on update cascade on delete cascade,
    person_id bigint not null
        references people
            on update cascade on delete cascade,
    constraint quote_people_pk
        primary key (person_id, quote_id)
);

alter table quote_people
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on quote_people to anon;

grant delete, insert, references, select, trigger, truncate, update on quote_people to authenticated;

grant delete, insert, references, select, trigger, truncate, update on quote_people to service_role;

grant delete, insert, references, select, trigger, truncate, update on quotes to anon;

grant delete, insert, references, select, trigger, truncate, update on quotes to authenticated;

grant delete, insert, references, select, trigger, truncate, update on quotes to service_role;

create table roles
(
    id   bigint generated by default as identity
        primary key,
    name varchar not null
        unique
);

alter table roles
    owner to postgres;

grant select, update, usage on sequence roles_id_seq to anon;

grant select, update, usage on sequence roles_id_seq to authenticated;

grant select, update, usage on sequence roles_id_seq to service_role;

grant delete, insert, references, select, trigger, truncate, update on roles to anon;

grant delete, insert, references, select, trigger, truncate, update on roles to authenticated;

grant delete, insert, references, select, trigger, truncate, update on roles to service_role;

create table users
(
    id              bigint generated by default as identity
        primary key,
    username        varchar                                   not null,
    password_hash   varchar                                   not null,
    user_auth_token varchar                                   not null,
    role            varchar default 'USER'::character varying not null
        references roles (name)
            on update cascade on delete set default,
    person_id       bigint
                                                              references people
                                                                  on update cascade on delete set null,
    game_id         bigint                                    not null
        references games
            on update cascade on delete cascade
);

alter table users
    owner to postgres;

grant select, update, usage on sequence users_id_seq to anon;

grant select, update, usage on sequence users_id_seq to authenticated;

grant select, update, usage on sequence users_id_seq to service_role;

grant delete, insert, references, select, trigger, truncate, update on users to anon;

grant delete, insert, references, select, trigger, truncate, update on users to authenticated;

grant delete, insert, references, select, trigger, truncate, update on users to service_role;

create table votes
(
    id          bigint generated by default as identity
        primary key,
    category_id bigint
        references categories
            on update cascade on delete cascade,
    quote_id    bigint
        references quotes
            on update cascade on delete cascade,
    person_id   bigint
        references people
            on update cascade on delete cascade,
    round       smallint default '1'::smallint not null,
    game_id     bigint                         not null
        references games
            on update cascade on delete cascade
);

alter table votes
    owner to postgres;

grant select, update, usage on sequence votes_id_seq to anon;

grant select, update, usage on sequence votes_id_seq to authenticated;

grant select, update, usage on sequence votes_id_seq to service_role;

grant delete, insert, references, select, trigger, truncate, update on votes to anon;

grant delete, insert, references, select, trigger, truncate, update on votes to authenticated;

grant delete, insert, references, select, trigger, truncate, update on votes to service_role;

create view quotes_with_details
            (id, content, full_quote, round, game_id, category_id, category_name, person_id, person_name) as
SELECT q.id,
       q.content,
       q.full_quote,
       q.round,
       q.game_id,
       c.id   AS category_id,
       c.name AS category_name,
       p.id   AS person_id,
       p.name AS person_name
FROM quotes q
         LEFT JOIN quote_categories qc ON q.id = qc.quote_id
         LEFT JOIN categories c ON qc.category_id = c.id
         LEFT JOIN quote_people qp ON q.id = qp.quote_id
         LEFT JOIN people p ON qp.person_id = p.id;

alter table quotes_with_details
    owner to alex;

create view quotes_with_details_aggregated(id, content, full_quote, round, game_id, categories, people) as
SELECT id,
       content,
       full_quote,
       round,
       game_id,
       json_agg(DISTINCT jsonb_build_object('id', category_id, 'name', category_name)) AS categories,
       json_agg(DISTINCT jsonb_build_object('id', person_id, 'name', person_name))     AS people
FROM quotes_with_details
GROUP BY id, content, full_quote, round, game_id;

alter table quotes_with_details_aggregated
    owner to alex;

create function get_all_categories()
    returns TABLE(id bigint, name character varying)
    language plpgsql
as
$$
BEGIN
  RETURN QUERY SELECT cg.id, cg.name FROM categories cg;
END;
$$;

alter function get_all_categories() owner to postgres;

grant execute on function get_all_categories() to anon;

grant execute on function get_all_categories() to authenticated;

grant execute on function get_all_categories() to service_role;

create function get_all_people()
    returns TABLE(id bigint, name text)
    language plpgsql
as
$$
BEGIN
  RETURN QUERY SELECT id, name FROM people;
END;
$$;

alter function get_all_people() owner to postgres;

grant execute on function get_all_people() to anon;

grant execute on function get_all_people() to authenticated;

grant execute on function get_all_people() to service_role;

create function get_quotes_with_details()
    returns TABLE(quote_id integer, quote_text text, categories text[], people text[])
    language plpgsql
as
$$
BEGIN
    RETURN QUERY
    SELECT
        q.id AS quote_id,
        q.content AS quote_text,
        ARRAY(SELECT c.id FROM categories c JOIN quote_categories qc ON c.id = qc.category_id WHERE qc.quote_id = q.id) AS categories,
        ARRAY(SELECT p.id FROM people p JOIN quote_people qp ON p.id = qp.people_id WHERE qp.quote_id = q.id) AS people
    FROM
        quotes q;
END;
$$;

alter function get_quotes_with_details() owner to postgres;

grant execute on function get_quotes_with_details() to anon;

grant execute on function get_quotes_with_details() to authenticated;

grant execute on function get_quotes_with_details() to service_role;

create function getselfvotes(param_game_id bigint)
    returns TABLE(person character varying, times_voted_for_themselves bigint)
    language plpgsql
as
$$
BEGIN
    RETURN QUERY
    SELECT p.name as Person, COUNT(p.name) as Times_voted_for_themselves
    FROM votes as v
    JOIN people p on p.id = v.person_id
    JOIN quotes q on q.id = v.quote_id
    JOIN categories c on c.id = v.category_id
    INNER JOIN quote_people qp ON qp.quote_id = v.quote_id
    WHERE qp.person_id = v.person_id and v.game_id = param_game_id
    GROUP BY p.name
    ORDER BY times_voted_for_themselves DESC;

END;
$$;

alter function getselfvotes(bigint) owner to postgres;

grant execute on function getselfvotes(bigint) to anon;

grant execute on function getselfvotes(bigint) to authenticated;

grant execute on function getselfvotes(bigint) to service_role;

create function gettopquotes(param_round integer, param_game_id bigint, param_count bigint)
    returns TABLE(count bigint, id bigint, content character varying, full_quote character varying, category_id bigint, category_name character varying)
    language plpgsql
as
$$
BEGIN
    RETURN QUERY
    WITH RankedQuotes AS (
        SELECT
            COUNT(q.id) AS count,
            q.id,
            q.content,
            q.full_quote,
            c.id as category_id,
            c.name as category_name,
            ROW_NUMBER() OVER (PARTITION BY c.id ORDER BY COUNT(q.id) DESC) AS rank
        FROM
            votes v
            JOIN quotes q ON q.id = v.quote_id
            JOIN categories c ON c.id = v.category_id
        WHERE v.game_id = param_game_id and v.round = param_round
        GROUP BY q.id, c.id
    )
    SELECT
        rq.count,
        rq.id,
        rq.content,
        rq.full_quote,
        rq.category_id,
        rq.category_name
    FROM
        RankedQuotes AS rq
    WHERE
        rank <= param_count
    ORDER BY
        category_id,
        count DESC,
        rank;

    -- You can add additional logic or return statements as needed.
END;
$$;

alter function gettopquotes(integer, bigint, bigint) owner to postgres;

grant execute on function gettopquotes(integer, bigint, bigint) to anon;

grant execute on function gettopquotes(integer, bigint, bigint) to authenticated;

grant execute on function gettopquotes(integer, bigint, bigint) to service_role;

